INSERT INTO covoiturage.ville (id, name, gouv_id) VALUES (1, 'Tunis', 1);
INSERT INTO covoiturage.ville (id, name, gouv_id) VALUES (2, 'Bardo', 1);
INSERT INTO covoiturage.ville (id, name, gouv_id) VALUES (3, 'Kram', 1);
INSERT INTO covoiturage.ville (id, name, gouv_id) VALUES (4, 'Goulette', 1);
INSERT INTO covoiturage.ville (id, name, gouv_id) VALUES (5, 'Carthage', 1);
INSERT INTO covoiturage.ville (id, name, gouv_id) VALUES (6, 'Sidi Bou Said', 1);
INSERT INTO covoiturage.ville (id, name, gouv_id) VALUES (7, 'Marsa', 1);
INSERT INTO covoiturage.ville (id, name, gouv_id) VALUES (8, 'Sidi Hassine', 1);
INSERT INTO covoiturage.ville (id, name, gouv_id) VALUES (9, 'Ariana', 2);
INSERT INTO covoiturage.ville (id, name, gouv_id) VALUES (10, 'Soukra', 2);
INSERT INTO covoiturage.ville (id, name, gouv_id) VALUES (11, 'Raoued', 2);
INSERT INTO covoiturage.ville (id, name, gouv_id) VALUES (12, 'Kalâat el-Andalous', 2);
INSERT INTO covoiturage.ville (id, name, gouv_id) VALUES (13, 'Sidi Thabet', 2);
INSERT INTO covoiturage.ville (id, name, gouv_id) VALUES (14, 'Ettadhamen-Mnihla', 2);
INSERT INTO covoiturage.ville (id, name, gouv_id) VALUES (15, 'Ben Arous', 3);
INSERT INTO covoiturage.ville (id, name, gouv_id) VALUES (16, 'El Mourouj', 3);
INSERT INTO covoiturage.ville (id, name, gouv_id) VALUES (17, 'Hammam Lif', 3);
INSERT INTO covoiturage.ville (id, name, gouv_id) VALUES (18, 'Hammam Chott', 3);
INSERT INTO covoiturage.ville (id, name, gouv_id) VALUES (19, 'Bou Mhel el-Bassatine', 3);
INSERT INTO covoiturage.ville (id, name, gouv_id) VALUES (20, 'Ezzahra', 3);
INSERT INTO covoiturage.ville (id, name, gouv_id) VALUES (21, 'Radès', 3);
INSERT INTO covoiturage.ville (id, name, gouv_id) VALUES (22, 'Mégrine', 3);
INSERT INTO covoiturage.ville (id, name, gouv_id) VALUES (23, 'Mohamedia-Fouchana', 3);
INSERT INTO covoiturage.ville (id, name, gouv_id) VALUES (24, 'Mornag', 3);
INSERT INTO covoiturage.ville (id, name, gouv_id) VALUES (25, 'Khalidia', 3);
INSERT INTO covoiturage.ville (id, name, gouv_id) VALUES (26, 'Manouba', 4);
INSERT INTO covoiturage.ville (id, name, gouv_id) VALUES (27, 'Den Den', 4);
INSERT INTO covoiturage.ville (id, name, gouv_id) VALUES (28, 'Douar Hicher', 4);
INSERT INTO covoiturage.ville (id, name, gouv_id) VALUES (29, 'Oued Ellil', 4);
INSERT INTO covoiturage.ville (id, name, gouv_id) VALUES (30, 'Mornaguia', 4);
INSERT INTO covoiturage.ville (id, name, gouv_id) VALUES (31, 'Borj El Amri', 4);
INSERT INTO covoiturage.ville (id, name, gouv_id) VALUES (32, 'Djedeida', 4);
INSERT INTO covoiturage.ville (id, name, gouv_id) VALUES (33, 'Tebourba', 4);
INSERT INTO covoiturage.ville (id, name, gouv_id) VALUES (34, 'El Battan', 4);
INSERT INTO covoiturage.ville (id, name, gouv_id) VALUES (35, 'Nabeul', 5);
INSERT INTO covoiturage.ville (id, name, gouv_id) VALUES (36, 'Dar Chaabane', 5);
INSERT INTO covoiturage.ville (id, name, gouv_id) VALUES (37, 'Béni Khiar', 5);
INSERT INTO covoiturage.ville (id, name, gouv_id) VALUES (38, 'El Maâmoura', 5);
INSERT INTO covoiturage.ville (id, name, gouv_id) VALUES (39, 'Somâa', 5);
INSERT INTO covoiturage.ville (id, name, gouv_id) VALUES (40, 'Korba', 5);
INSERT INTO covoiturage.ville (id, name, gouv_id) VALUES (41, 'Tazerka', 5);
INSERT INTO covoiturage.ville (id, name, gouv_id) VALUES (42, 'Menzel Temime', 5);
INSERT INTO covoiturage.ville (id, name, gouv_id) VALUES (43, 'Menzel Horr', 5);
INSERT INTO covoiturage.ville (id, name, gouv_id) VALUES (44, 'El Mida', 5);
INSERT INTO covoiturage.ville (id, name, gouv_id) VALUES (45, 'Kelibia', 5);
INSERT INTO covoiturage.ville (id, name, gouv_id) VALUES (46, 'Azmour', 5);
INSERT INTO covoiturage.ville (id, name, gouv_id) VALUES (47, 'Hammam Ghezèze', 5);
INSERT INTO covoiturage.ville (id, name, gouv_id) VALUES (48, 'Dar Allouch', 5);
INSERT INTO covoiturage.ville (id, name, gouv_id) VALUES (49, 'El Haouaria', 5);
INSERT INTO covoiturage.ville (id, name, gouv_id) VALUES (50, 'Takelsa', 5);
INSERT INTO covoiturage.ville (id, name, gouv_id) VALUES (51, 'Soliman', 5);
INSERT INTO covoiturage.ville (id, name, gouv_id) VALUES (52, 'Korbous', 5);
INSERT INTO covoiturage.ville (id, name, gouv_id) VALUES (53, 'Menzel Bouzelfa', 5);
INSERT INTO covoiturage.ville (id, name, gouv_id) VALUES (54, 'Béni Khalled', 5);
INSERT INTO covoiturage.ville (id, name, gouv_id) VALUES (55, 'Zaouiet Djedidi', 5);
INSERT INTO covoiturage.ville (id, name, gouv_id) VALUES (56, 'Grombalia', 5);
INSERT INTO covoiturage.ville (id, name, gouv_id) VALUES (57, 'Bou Argoub', 5);
INSERT INTO covoiturage.ville (id, name, gouv_id) VALUES (58, 'Hammamet', 5);
INSERT INTO covoiturage.ville (id, name, gouv_id) VALUES (59, 'Zaghouan', 6);
INSERT INTO covoiturage.ville (id, name, gouv_id) VALUES (60, 'Zriba', 6);
INSERT INTO covoiturage.ville (id, name, gouv_id) VALUES (61, 'Bir Mcherga', 6);
INSERT INTO covoiturage.ville (id, name, gouv_id) VALUES (62, 'Djebel Oust', 6);
INSERT INTO covoiturage.ville (id, name, gouv_id) VALUES (63, 'El Fahs', 6);
INSERT INTO covoiturage.ville (id, name, gouv_id) VALUES (64, 'Nadhour', 6);
INSERT INTO covoiturage.ville (id, name, gouv_id) VALUES (65, 'Bizerte', 7);
INSERT INTO covoiturage.ville (id, name, gouv_id) VALUES (66, 'Sejnane', 7);
INSERT INTO covoiturage.ville (id, name, gouv_id) VALUES (67, 'Mateur', 7);
INSERT INTO covoiturage.ville (id, name, gouv_id) VALUES (68, 'Menzel Bourguiba', 7);
INSERT INTO covoiturage.ville (id, name, gouv_id) VALUES (69, 'Tinja', 7);
INSERT INTO covoiturage.ville (id, name, gouv_id) VALUES (70, 'Ghar al Milh', 7);
INSERT INTO covoiturage.ville (id, name, gouv_id) VALUES (71, 'Aousja', 7);
INSERT INTO covoiturage.ville (id, name, gouv_id) VALUES (72, 'Menzel Jemil', 7);
INSERT INTO covoiturage.ville (id, name, gouv_id) VALUES (73, 'Menzel Abderrahmane', 7);
INSERT INTO covoiturage.ville (id, name, gouv_id) VALUES (74, 'El Alia', 7);
INSERT INTO covoiturage.ville (id, name, gouv_id) VALUES (75, 'Ras Jebel', 7);
INSERT INTO covoiturage.ville (id, name, gouv_id) VALUES (76, 'Metline', 7);
INSERT INTO covoiturage.ville (id, name, gouv_id) VALUES (77, 'Raf Raf', 7);
INSERT INTO covoiturage.ville (id, name, gouv_id) VALUES (78, 'Béja', 8);
INSERT INTO covoiturage.ville (id, name, gouv_id) VALUES (79, 'El Maâgoula', 8);
INSERT INTO covoiturage.ville (id, name, gouv_id) VALUES (80, 'Zahret Medien', 8);
INSERT INTO covoiturage.ville (id, name, gouv_id) VALUES (81, 'Nefza', 8);
INSERT INTO covoiturage.ville (id, name, gouv_id) VALUES (82, 'Téboursouk', 8);
INSERT INTO covoiturage.ville (id, name, gouv_id) VALUES (83, 'Testour', 8);
INSERT INTO covoiturage.ville (id, name, gouv_id) VALUES (84, 'Goubellat', 8);
INSERT INTO covoiturage.ville (id, name, gouv_id) VALUES (85, 'Majaz al Bab', 8);
INSERT INTO covoiturage.ville (id, name, gouv_id) VALUES (86, 'Jendouba', 9);
INSERT INTO covoiturage.ville (id, name, gouv_id) VALUES (87, 'Bou Salem', 9);
INSERT INTO covoiturage.ville (id, name, gouv_id) VALUES (88, 'Tabarka', 9);
INSERT INTO covoiturage.ville (id, name, gouv_id) VALUES (89, 'Aïn Draham', 9);
INSERT INTO covoiturage.ville (id, name, gouv_id) VALUES (90, 'Fernana', 9);
INSERT INTO covoiturage.ville (id, name, gouv_id) VALUES (91, 'Beni M''Tir', 9);
INSERT INTO covoiturage.ville (id, name, gouv_id) VALUES (92, 'Ghardimaou', 9);
INSERT INTO covoiturage.ville (id, name, gouv_id) VALUES (93, 'Oued Melliz', 9);
INSERT INTO covoiturage.ville (id, name, gouv_id) VALUES (94, 'El Kef', 10);
INSERT INTO covoiturage.ville (id, name, gouv_id) VALUES (95, 'Nebeur', 10);
INSERT INTO covoiturage.ville (id, name, gouv_id) VALUES (96, 'Touiref', 10);
INSERT INTO covoiturage.ville (id, name, gouv_id) VALUES (97, 'Sakiet Sidi Youssef', 10);
INSERT INTO covoiturage.ville (id, name, gouv_id) VALUES (98, 'Tajerouine', 10);
INSERT INTO covoiturage.ville (id, name, gouv_id) VALUES (99, 'Menzel Salem', 10);
INSERT INTO covoiturage.ville (id, name, gouv_id) VALUES (100, 'Kalaat es Senam', 10);
INSERT INTO covoiturage.ville (id, name, gouv_id) VALUES (101, 'Kalâat Khasba', 10);
INSERT INTO covoiturage.ville (id, name, gouv_id) VALUES (102, 'Jérissa', 10);
INSERT INTO covoiturage.ville (id, name, gouv_id) VALUES (103, 'El Ksour', 10);
INSERT INTO covoiturage.ville (id, name, gouv_id) VALUES (104, 'Dahmani', 10);
INSERT INTO covoiturage.ville (id, name, gouv_id) VALUES (105, 'Sers', 10);
INSERT INTO covoiturage.ville (id, name, gouv_id) VALUES (106, 'Siliana', 11);
INSERT INTO covoiturage.ville (id, name, gouv_id) VALUES (107, 'Bou Arada', 11);
INSERT INTO covoiturage.ville (id, name, gouv_id) VALUES (108, 'Gaâfour', 11);
INSERT INTO covoiturage.ville (id, name, gouv_id) VALUES (109, 'El Krib', 11);
INSERT INTO covoiturage.ville (id, name, gouv_id) VALUES (110, 'Sidi Bou Rouis', 11);
INSERT INTO covoiturage.ville (id, name, gouv_id) VALUES (111, 'Maktar', 11);
INSERT INTO covoiturage.ville (id, name, gouv_id) VALUES (112, 'Rouhia', 11);
INSERT INTO covoiturage.ville (id, name, gouv_id) VALUES (113, 'Kesra', 11);
INSERT INTO covoiturage.ville (id, name, gouv_id) VALUES (114, 'Bargou', 11);
INSERT INTO covoiturage.ville (id, name, gouv_id) VALUES (115, 'El Aroussa', 11);
INSERT INTO covoiturage.ville (id, name, gouv_id) VALUES (116, 'Sousse', 12);
INSERT INTO covoiturage.ville (id, name, gouv_id) VALUES (117, 'Ksibet Thrayet', 12);
INSERT INTO covoiturage.ville (id, name, gouv_id) VALUES (118, 'Ezzouhour', 12);
INSERT INTO covoiturage.ville (id, name, gouv_id) VALUES (119, 'Zaouiet Sousse', 12);
INSERT INTO covoiturage.ville (id, name, gouv_id) VALUES (120, 'Hammam Sousse', 12);
INSERT INTO covoiturage.ville (id, name, gouv_id) VALUES (121, 'Akouda', 12);
INSERT INTO covoiturage.ville (id, name, gouv_id) VALUES (122, 'Kalâa Kebira', 12);
INSERT INTO covoiturage.ville (id, name, gouv_id) VALUES (123, 'Sidi Bou Ali', 12);
INSERT INTO covoiturage.ville (id, name, gouv_id) VALUES (124, 'Hergla', 12);
INSERT INTO covoiturage.ville (id, name, gouv_id) VALUES (125, 'Enfidha', 12);
INSERT INTO covoiturage.ville (id, name, gouv_id) VALUES (126, 'Bouficha', 12);
INSERT INTO covoiturage.ville (id, name, gouv_id) VALUES (127, 'Sidi El Hani', 12);
INSERT INTO covoiturage.ville (id, name, gouv_id) VALUES (128, 'M''saken', 12);
INSERT INTO covoiturage.ville (id, name, gouv_id) VALUES (129, 'Kalâa Seghira', 12);
INSERT INTO covoiturage.ville (id, name, gouv_id) VALUES (130, 'Messaadine', 12);
INSERT INTO covoiturage.ville (id, name, gouv_id) VALUES (131, 'Kondar', 12);
INSERT INTO covoiturage.ville (id, name, gouv_id) VALUES (132, 'Monastir', 13);
INSERT INTO covoiturage.ville (id, name, gouv_id) VALUES (133, 'Khniss', 13);
INSERT INTO covoiturage.ville (id, name, gouv_id) VALUES (134, 'Ouerdanin', 13);
INSERT INTO covoiturage.ville (id, name, gouv_id) VALUES (135, 'Sahline Moôtmar', 13);
INSERT INTO covoiturage.ville (id, name, gouv_id) VALUES (136, 'Sidi Ameur', 13);
INSERT INTO covoiturage.ville (id, name, gouv_id) VALUES (137, 'Zéramdine', 13);
INSERT INTO covoiturage.ville (id, name, gouv_id) VALUES (138, 'Beni Hassen', 13);
INSERT INTO covoiturage.ville (id, name, gouv_id) VALUES (139, 'Ghenada', 13);
INSERT INTO covoiturage.ville (id, name, gouv_id) VALUES (140, 'Jemmal', 13);
INSERT INTO covoiturage.ville (id, name, gouv_id) VALUES (141, 'Menzel Kamel', 13);
INSERT INTO covoiturage.ville (id, name, gouv_id) VALUES (142, 'Zaouiet Kontoch', 13);
INSERT INTO covoiturage.ville (id, name, gouv_id) VALUES (143, 'Bembla-Mnara', 13);
INSERT INTO covoiturage.ville (id, name, gouv_id) VALUES (144, 'Menzel Ennour', 13);
INSERT INTO covoiturage.ville (id, name, gouv_id) VALUES (145, 'El Masdour', 13);
INSERT INTO covoiturage.ville (id, name, gouv_id) VALUES (146, 'Moknine', 13);
INSERT INTO covoiturage.ville (id, name, gouv_id) VALUES (147, 'Sidi Bennour', 13);
INSERT INTO covoiturage.ville (id, name, gouv_id) VALUES (148, 'Menzel Farsi', 13);
INSERT INTO covoiturage.ville (id, name, gouv_id) VALUES (149, 'Amiret El Fhoul', 13);
INSERT INTO covoiturage.ville (id, name, gouv_id) VALUES (150, 'Amiret Touazra', 13);
INSERT INTO covoiturage.ville (id, name, gouv_id) VALUES (151, 'Amiret El Hojjaj', 13);
INSERT INTO covoiturage.ville (id, name, gouv_id) VALUES (152, 'Cherahil', 13);
INSERT INTO covoiturage.ville (id, name, gouv_id) VALUES (153, 'Bekalta', 13);
INSERT INTO covoiturage.ville (id, name, gouv_id) VALUES (154, 'Téboulba', 13);
INSERT INTO covoiturage.ville (id, name, gouv_id) VALUES (155, 'Ksar Hellal', 13);
INSERT INTO covoiturage.ville (id, name, gouv_id) VALUES (156, 'Ksibet El Mediouni', 13);
INSERT INTO covoiturage.ville (id, name, gouv_id) VALUES (157, 'Benen Bodher', 13);
INSERT INTO covoiturage.ville (id, name, gouv_id) VALUES (158, 'Touza', 13);
INSERT INTO covoiturage.ville (id, name, gouv_id) VALUES (159, 'Sayada', 13);
INSERT INTO covoiturage.ville (id, name, gouv_id) VALUES (160, 'Lemta', 13);
INSERT INTO covoiturage.ville (id, name, gouv_id) VALUES (161, 'Bouhjar', 13);
INSERT INTO covoiturage.ville (id, name, gouv_id) VALUES (162, 'Menzel Hayet', 13);
INSERT INTO covoiturage.ville (id, name, gouv_id) VALUES (163, 'Mahdia', 14);
INSERT INTO covoiturage.ville (id, name, gouv_id) VALUES (164, 'Rejiche', 14);
INSERT INTO covoiturage.ville (id, name, gouv_id) VALUES (165, 'Bou Merdes', 14);
INSERT INTO covoiturage.ville (id, name, gouv_id) VALUES (166, 'Ouled Chamekh', 14);
INSERT INTO covoiturage.ville (id, name, gouv_id) VALUES (167, 'Chorbane', 14);
INSERT INTO covoiturage.ville (id, name, gouv_id) VALUES (168, 'Hebira', 14);
INSERT INTO covoiturage.ville (id, name, gouv_id) VALUES (169, 'Essouassi', 14);
INSERT INTO covoiturage.ville (id, name, gouv_id) VALUES (170, 'El Djem', 14);
INSERT INTO covoiturage.ville (id, name, gouv_id) VALUES (171, 'Kerker', 14);
INSERT INTO covoiturage.ville (id, name, gouv_id) VALUES (172, 'Chebba', 14);
INSERT INTO covoiturage.ville (id, name, gouv_id) VALUES (173, 'Melloulèche', 14);
INSERT INTO covoiturage.ville (id, name, gouv_id) VALUES (174, 'Sidi Alouane', 14);
INSERT INTO covoiturage.ville (id, name, gouv_id) VALUES (175, 'Ksour Essef', 14);
INSERT INTO covoiturage.ville (id, name, gouv_id) VALUES (176, 'El Bradâa', 14);
INSERT INTO covoiturage.ville (id, name, gouv_id) VALUES (177, 'Sfax', 15);
INSERT INTO covoiturage.ville (id, name, gouv_id) VALUES (178, 'Sakiet Ezzit', 15);
INSERT INTO covoiturage.ville (id, name, gouv_id) VALUES (179, 'Chihia', 15);
INSERT INTO covoiturage.ville (id, name, gouv_id) VALUES (180, 'Sakiet Eddaïer', 15);
INSERT INTO covoiturage.ville (id, name, gouv_id) VALUES (181, 'Gremda', 15);
INSERT INTO covoiturage.ville (id, name, gouv_id) VALUES (182, 'El Ain', 15);
INSERT INTO covoiturage.ville (id, name, gouv_id) VALUES (183, 'Thyna', 15);
INSERT INTO covoiturage.ville (id, name, gouv_id) VALUES (184, 'Agareb', 15);
INSERT INTO covoiturage.ville (id, name, gouv_id) VALUES (185, 'Jebiniana', 15);
INSERT INTO covoiturage.ville (id, name, gouv_id) VALUES (186, 'El Hencha', 15);
INSERT INTO covoiturage.ville (id, name, gouv_id) VALUES (187, 'Menzel Chaker', 15);
INSERT INTO covoiturage.ville (id, name, gouv_id) VALUES (188, 'Ghraïba', 15);
INSERT INTO covoiturage.ville (id, name, gouv_id) VALUES (189, 'Bir Ali Ben Khélifa', 15);
INSERT INTO covoiturage.ville (id, name, gouv_id) VALUES (190, 'Skhira', 15);
INSERT INTO covoiturage.ville (id, name, gouv_id) VALUES (191, 'Mahares', 15);
INSERT INTO covoiturage.ville (id, name, gouv_id) VALUES (192, 'Kerkennah', 15);
INSERT INTO covoiturage.ville (id, name, gouv_id) VALUES (193, 'Kairouan', 16);
INSERT INTO covoiturage.ville (id, name, gouv_id) VALUES (194, 'Chebika, Kairouan', 16);
INSERT INTO covoiturage.ville (id, name, gouv_id) VALUES (195, 'Sbikha', 16);
INSERT INTO covoiturage.ville (id, name, gouv_id) VALUES (196, 'Oueslatia', 16);
INSERT INTO covoiturage.ville (id, name, gouv_id) VALUES (197, 'Aïn Djeloula', 16);
INSERT INTO covoiturage.ville (id, name, gouv_id) VALUES (198, 'Haffouz', 16);
INSERT INTO covoiturage.ville (id, name, gouv_id) VALUES (199, 'Alaâ', 16);
INSERT INTO covoiturage.ville (id, name, gouv_id) VALUES (200, 'Hajeb El Ayoun', 16);
INSERT INTO covoiturage.ville (id, name, gouv_id) VALUES (201, 'Nasrallah', 16);
INSERT INTO covoiturage.ville (id, name, gouv_id) VALUES (202, 'Menzel Mehiri', 16);
INSERT INTO covoiturage.ville (id, name, gouv_id) VALUES (203, 'Echrarda', 16);
INSERT INTO covoiturage.ville (id, name, gouv_id) VALUES (204, 'Bou Hajla', 16);
INSERT INTO covoiturage.ville (id, name, gouv_id) VALUES (205, 'Kasserine', 17);
INSERT INTO covoiturage.ville (id, name, gouv_id) VALUES (206, 'Sbeitla', 17);
INSERT INTO covoiturage.ville (id, name, gouv_id) VALUES (207, 'Sbiba', 17);
INSERT INTO covoiturage.ville (id, name, gouv_id) VALUES (208, 'Jedelienne', 17);
INSERT INTO covoiturage.ville (id, name, gouv_id) VALUES (209, 'Thala', 17);
INSERT INTO covoiturage.ville (id, name, gouv_id) VALUES (210, 'Haïdra', 17);
INSERT INTO covoiturage.ville (id, name, gouv_id) VALUES (211, 'Foussana', 17);
INSERT INTO covoiturage.ville (id, name, gouv_id) VALUES (212, 'Fériana', 17);
INSERT INTO covoiturage.ville (id, name, gouv_id) VALUES (213, 'Thélepte', 17);
INSERT INTO covoiturage.ville (id, name, gouv_id) VALUES (214, 'Magel Bel Abbès', 17);
INSERT INTO covoiturage.ville (id, name, gouv_id) VALUES (215, 'Sidi Bouzid', 18);
INSERT INTO covoiturage.ville (id, name, gouv_id) VALUES (216, 'Jilma', 18);
INSERT INTO covoiturage.ville (id, name, gouv_id) VALUES (217, 'Cebalet', 18);
INSERT INTO covoiturage.ville (id, name, gouv_id) VALUES (218, 'Bir El Hafey', 18);
INSERT INTO covoiturage.ville (id, name, gouv_id) VALUES (219, 'Sidi Ali Ben Aoun', 18);
INSERT INTO covoiturage.ville (id, name, gouv_id) VALUES (220, 'Menzel Bouzaiane', 18);
INSERT INTO covoiturage.ville (id, name, gouv_id) VALUES (221, 'Meknassy', 18);
INSERT INTO covoiturage.ville (id, name, gouv_id) VALUES (222, 'Mezzouna', 18);
INSERT INTO covoiturage.ville (id, name, gouv_id) VALUES (223, 'Regueb', 18);
INSERT INTO covoiturage.ville (id, name, gouv_id) VALUES (224, 'Ouled Haffouz', 18);
INSERT INTO covoiturage.ville (id, name, gouv_id) VALUES (225, 'Gabès', 19);
INSERT INTO covoiturage.ville (id, name, gouv_id) VALUES (226, 'Chenini Nahal', 19);
INSERT INTO covoiturage.ville (id, name, gouv_id) VALUES (227, 'Ghannouch', 19);
INSERT INTO covoiturage.ville (id, name, gouv_id) VALUES (228, 'Métouia', 19);
INSERT INTO covoiturage.ville (id, name, gouv_id) VALUES (229, 'Oudhref', 19);
INSERT INTO covoiturage.ville (id, name, gouv_id) VALUES (230, 'El Hamma', 19);
INSERT INTO covoiturage.ville (id, name, gouv_id) VALUES (231, 'Matmata', 19);
INSERT INTO covoiturage.ville (id, name, gouv_id) VALUES (232, 'Nouvelle Matmata', 19);
INSERT INTO covoiturage.ville (id, name, gouv_id) VALUES (233, 'Mareth', 19);
INSERT INTO covoiturage.ville (id, name, gouv_id) VALUES (234, 'Zarat', 19);
INSERT INTO covoiturage.ville (id, name, gouv_id) VALUES (235, 'Medenine', 20);
INSERT INTO covoiturage.ville (id, name, gouv_id) VALUES (236, 'Beni Khedache', 20);
INSERT INTO covoiturage.ville (id, name, gouv_id) VALUES (237, 'Ben Gardane', 20);
INSERT INTO covoiturage.ville (id, name, gouv_id) VALUES (238, 'Zarzis', 20);
INSERT INTO covoiturage.ville (id, name, gouv_id) VALUES (239, 'Houmt El Souk', 20);
INSERT INTO covoiturage.ville (id, name, gouv_id) VALUES (240, 'Midoun', 20);
INSERT INTO covoiturage.ville (id, name, gouv_id) VALUES (241, 'Ajim', 20);
INSERT INTO covoiturage.ville (id, name, gouv_id) VALUES (242, 'Tataouine', 21);
INSERT INTO covoiturage.ville (id, name, gouv_id) VALUES (243, 'Bir Lahmar', 21);
INSERT INTO covoiturage.ville (id, name, gouv_id) VALUES (244, 'Ghomrassen', 21);
INSERT INTO covoiturage.ville (id, name, gouv_id) VALUES (245, 'Dehiba', 21);
INSERT INTO covoiturage.ville (id, name, gouv_id) VALUES (246, 'Remada', 21);
INSERT INTO covoiturage.ville (id, name, gouv_id) VALUES (247, 'Gafsa', 22);
INSERT INTO covoiturage.ville (id, name, gouv_id) VALUES (248, 'El Ksar', 22);
INSERT INTO covoiturage.ville (id, name, gouv_id) VALUES (249, 'Moularès', 22);
INSERT INTO covoiturage.ville (id, name, gouv_id) VALUES (250, 'Redeyef', 22);
INSERT INTO covoiturage.ville (id, name, gouv_id) VALUES (251, 'Métlaoui', 22);
INSERT INTO covoiturage.ville (id, name, gouv_id) VALUES (252, 'Mdhila', 22);
INSERT INTO covoiturage.ville (id, name, gouv_id) VALUES (253, 'El Guettar', 22);
INSERT INTO covoiturage.ville (id, name, gouv_id) VALUES (254, 'Sened', 22);
INSERT INTO covoiturage.ville (id, name, gouv_id) VALUES (255, 'Tozeur', 23);
INSERT INTO covoiturage.ville (id, name, gouv_id) VALUES (256, 'Degache', 23);
INSERT INTO covoiturage.ville (id, name, gouv_id) VALUES (257, 'Hamet Jerid', 23);
INSERT INTO covoiturage.ville (id, name, gouv_id) VALUES (258, 'Nafta', 23);
INSERT INTO covoiturage.ville (id, name, gouv_id) VALUES (259, 'Tamerza', 23);
INSERT INTO covoiturage.ville (id, name, gouv_id) VALUES (260, 'Kebili', 24);
INSERT INTO covoiturage.ville (id, name, gouv_id) VALUES (261, 'Djemna', 24);
INSERT INTO covoiturage.ville (id, name, gouv_id) VALUES (262, 'Douz', 24);
INSERT INTO covoiturage.ville (id, name, gouv_id) VALUES (263, 'El Golâa', 24);
INSERT INTO covoiturage.ville (id, name, gouv_id) VALUES (264, 'Souk Lahad', 24);