INSERT INTO covoiturage.gouvernorat (id, name) VALUES (1, 'Tunis');
INSERT INTO covoiturage.gouvernorat (id, name) VALUES (2, 'Ariana');
INSERT INTO covoiturage.gouvernorat (id, name) VALUES (3, 'Ben Arous');
INSERT INTO covoiturage.gouvernorat (id, name) VALUES (4, 'Manouba');
INSERT INTO covoiturage.gouvernorat (id, name) VALUES (5, 'Nabeul');
INSERT INTO covoiturage.gouvernorat (id, name) VALUES (6, 'Zaghouan');
INSERT INTO covoiturage.gouvernorat (id, name) VALUES (7, 'Bizerte');
INSERT INTO covoiturage.gouvernorat (id, name) VALUES (8, 'Béja');
INSERT INTO covoiturage.gouvernorat (id, name) VALUES (9, 'Jendouba');
INSERT INTO covoiturage.gouvernorat (id, name) VALUES (10, 'Kef');
INSERT INTO covoiturage.gouvernorat (id, name) VALUES (11, 'Siliana');
INSERT INTO covoiturage.gouvernorat (id, name) VALUES (12, 'Sousse');
INSERT INTO covoiturage.gouvernorat (id, name) VALUES (13, 'Monastir');
INSERT INTO covoiturage.gouvernorat (id, name) VALUES (14, 'Mahdia');
INSERT INTO covoiturage.gouvernorat (id, name) VALUES (15, 'Sfax');
INSERT INTO covoiturage.gouvernorat (id, name) VALUES (16, 'Kairouan');
INSERT INTO covoiturage.gouvernorat (id, name) VALUES (17, 'Kasserine');
INSERT INTO covoiturage.gouvernorat (id, name) VALUES (18, 'Sidi Bouzid');
INSERT INTO covoiturage.gouvernorat (id, name) VALUES (19, 'Gabès');
INSERT INTO covoiturage.gouvernorat (id, name) VALUES (20, 'Mednine');
INSERT INTO covoiturage.gouvernorat (id, name) VALUES (21, 'Tataouine');
INSERT INTO covoiturage.gouvernorat (id, name) VALUES (22, 'Gafsa');
INSERT INTO covoiturage.gouvernorat (id, name) VALUES (23, 'Tozeur');
INSERT INTO covoiturage.gouvernorat (id, name) VALUES (24, 'Kebili');